visitor -> molinex "Explores product information and requests commercial contact through Molinex."
administrator -> molinex "Uses Molinex to administer users and supervise rice mill operations."
maintenanceTechnician -> molinex "Uses Molinex to manage machines, maintenance, anomalies and alerts."
productionOperator -> molinex "Uses Molinex to record production, quality and waste information."
sensorGateway -> molinex "Sends planned operational readings to Molinex." "HTTPS or MQTT"
molinex -> notificationService "Sends planned account and operational alert notifications to." "HTTPS API or SMTP"

visitor -> molinex.landingPage "Explores product information" "HTTPS"
administrator -> molinex.webHost "Uses" "HTTPS"
maintenanceTechnician -> molinex.webHost "Uses" "HTTPS"
productionOperator -> molinex.webHost "Uses" "HTTPS"
molinex.landingPage -> molinex.webHost "Redirects to" "HTTPS"
molinex.webHost -> molinex.webApplication "Delivers" "HTTPS"
molinex.landingPage -> molinex.apiApplication "Submits inquiries to" "JSON/HTTPS REST"
molinex.webApplication -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
sensorGateway -> molinex.apiApplication "Sends planned operational readings to" "HTTPS or MQTT"
molinex.apiApplication -> notificationService "Sends planned account and operational alert notifications through" "HTTPS API or SMTP"
molinex.apiApplication -> molinex.database "Persists data in" "Entity Framework Core / SQL"

visitor -> molinex.webApplication.commercialFeature "Uses"
administrator -> molinex.webApplication.identityFeature "Uses"
administrator -> molinex.webApplication.reportingFeature "Uses"
maintenanceTechnician -> molinex.webApplication.maintenanceFeature "Uses"
maintenanceTechnician -> molinex.webApplication.intelligenceFeature "Uses"
productionOperator -> molinex.webApplication.productionFeature "Uses"
productionOperator -> molinex.webApplication.qualityFeature "Uses"
molinex.webApplication.commercialFeature -> molinex.webApplication.frontendSharedKernel "Uses shared UI and HTTP infrastructure from"
molinex.webApplication.identityFeature -> molinex.webApplication.frontendSharedKernel "Uses shared UI and HTTP infrastructure from"
molinex.webApplication.productionFeature -> molinex.webApplication.frontendSharedKernel "Uses shared UI, HTTP infrastructure and domain values from"
molinex.webApplication.qualityFeature -> molinex.webApplication.frontendSharedKernel "Uses shared UI, HTTP infrastructure and domain values from"
molinex.webApplication.maintenanceFeature -> molinex.webApplication.frontendSharedKernel "Uses shared UI and HTTP infrastructure from"
molinex.webApplication.intelligenceFeature -> molinex.webApplication.frontendSharedKernel "Uses shared UI and HTTP infrastructure from"
molinex.webApplication.reportingFeature -> molinex.webApplication.frontendSharedKernel "Uses shared UI and HTTP infrastructure from"
molinex.webApplication.commercialFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.identityFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.productionFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.qualityFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.maintenanceFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.intelligenceFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.reportingFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"

molinex.webApplication.planCatalog -> molinex.webApplication.commercialApplication "Reads plans from"
molinex.webApplication.valuePropositionView -> molinex.webApplication.commercialApplication "Reads the value proposition from"
molinex.webApplication.commercialInquiryForm -> molinex.webApplication.commercialApplication "Submits inquiries through"
molinex.webApplication.planCatalog -> molinex.webApplication.commercialDomain "Displays"
molinex.webApplication.valuePropositionView -> molinex.webApplication.commercialDomain "Displays"
molinex.webApplication.commercialInquiryForm -> molinex.webApplication.commercialDomain "Builds"
molinex.webApplication.commercialApplication -> molinex.webApplication.commercialDomain "Holds"
molinex.webApplication.commercialApplication -> molinex.webApplication.commercialInfrastructure "Loads plans and submits inquiries through"
molinex.webApplication.commercialInfrastructure -> molinex.webApplication.commercialDomain "Builds"
molinex.webApplication.commercialInfrastructure -> molinex.apiApplication "Reads plans and submits inquiries using" "JSON/HTTPS REST"

molinex.webApplication.authenticationSection -> molinex.webApplication.identityApplication "Reads the session and signs out through"
molinex.webApplication.signInForm -> molinex.webApplication.identityApplication "Signs in through"
molinex.webApplication.userList -> molinex.webApplication.identityApplication "Reads and administers users through"
molinex.webApplication.userForm -> molinex.webApplication.identityApplication "Registers and updates users through"
molinex.webApplication.roleAssignmentForm -> molinex.webApplication.identityApplication "Assigns roles and permissions through"
molinex.webApplication.profileView -> molinex.webApplication.identityApplication "Reads and updates the profile through"
molinex.webApplication.authenticationSection -> molinex.webApplication.identityDomain "Displays"
molinex.webApplication.signInForm -> molinex.webApplication.identityDomain "Builds"
molinex.webApplication.userList -> molinex.webApplication.identityDomain "Displays"
molinex.webApplication.userForm -> molinex.webApplication.identityDomain "Builds"
molinex.webApplication.roleAssignmentForm -> molinex.webApplication.identityDomain "Builds"
molinex.webApplication.profileView -> molinex.webApplication.identityDomain "Displays and builds"
molinex.webApplication.identityApplication -> molinex.webApplication.identityDomain "Holds"
molinex.webApplication.identityApplication -> molinex.webApplication.identityInfrastructure "Authenticates and loads identity data through"
molinex.webApplication.identityInfrastructure -> molinex.webApplication.identityApplication "Reads the current session from"
molinex.webApplication.identityInfrastructure -> molinex.webApplication.identityDomain "Maps resources to"
molinex.webApplication.identityInfrastructure -> molinex.apiApplication "Invokes identity endpoints on" "JSON/HTTPS REST"

molinex.webApplication.rawMaterialReceptionList -> molinex.webApplication.productionApplication "Reads receptions and invokes actions on"
molinex.webApplication.rawMaterialReceptionForm -> molinex.webApplication.productionApplication "Submits reception operations through"
molinex.webApplication.productionBatchList -> molinex.webApplication.productionApplication "Reads batches and invokes actions on"
molinex.webApplication.productionBatchForm -> molinex.webApplication.productionApplication "Submits batch operations through"
molinex.webApplication.productionRecordList -> molinex.webApplication.productionApplication "Reads production records and invokes actions on"
molinex.webApplication.productionRecordForm -> molinex.webApplication.productionApplication "Submits production record operations through"
molinex.webApplication.productionHistoryView -> molinex.webApplication.productionApplication "Reads production history from"
molinex.webApplication.rawMaterialReceptionList -> molinex.webApplication.productionDomain "Displays"
molinex.webApplication.rawMaterialReceptionForm -> molinex.webApplication.productionDomain "Builds"
molinex.webApplication.productionBatchList -> molinex.webApplication.productionDomain "Displays"
molinex.webApplication.productionBatchForm -> molinex.webApplication.productionDomain "Builds"
molinex.webApplication.productionRecordList -> molinex.webApplication.productionDomain "Displays"
molinex.webApplication.productionRecordForm -> molinex.webApplication.productionDomain "Builds"
molinex.webApplication.productionHistoryView -> molinex.webApplication.productionDomain "Displays"
molinex.webApplication.productionApplication -> molinex.webApplication.productionDomain "Holds"
molinex.webApplication.productionApplication -> molinex.webApplication.productionInfrastructure "Loads and saves production data through"
molinex.webApplication.productionInfrastructure -> molinex.webApplication.productionDomain "Builds"
molinex.webApplication.productionInfrastructure -> molinex.apiApplication "Reads and writes production data using" "JSON/HTTPS REST"

molinex.webApplication.qualityAssessmentList -> molinex.webApplication.qualityApplication "Reads assessments from"
molinex.webApplication.qualityAssessmentForm -> molinex.webApplication.qualityApplication "Submits assessments through"
molinex.webApplication.wasteRecordList -> molinex.webApplication.qualityApplication "Reads waste records from"
molinex.webApplication.wasteRecordForm -> molinex.webApplication.qualityApplication "Submits waste records through"
molinex.webApplication.yieldIndicatorDashboard -> molinex.webApplication.qualityApplication "Reads indicators from"
molinex.webApplication.qualityComparisonView -> molinex.webApplication.qualityApplication "Requests comparisons through"
molinex.webApplication.qualityDeviationList -> molinex.webApplication.qualityApplication "Reads deviations from"
molinex.webApplication.qualityAssessmentList -> molinex.webApplication.qualityDomain "Displays"
molinex.webApplication.qualityAssessmentForm -> molinex.webApplication.qualityDomain "Builds"
molinex.webApplication.wasteRecordList -> molinex.webApplication.qualityDomain "Displays"
molinex.webApplication.wasteRecordForm -> molinex.webApplication.qualityDomain "Builds"
molinex.webApplication.yieldIndicatorDashboard -> molinex.webApplication.qualityDomain "Displays"
molinex.webApplication.qualityComparisonView -> molinex.webApplication.qualityDomain "Displays"
molinex.webApplication.qualityDeviationList -> molinex.webApplication.qualityDomain "Displays"
molinex.webApplication.qualityApplication -> molinex.webApplication.qualityDomain "Holds"
molinex.webApplication.qualityApplication -> molinex.webApplication.qualityInfrastructure "Loads and saves quality data through"
molinex.webApplication.qualityInfrastructure -> molinex.webApplication.qualityDomain "Builds"
molinex.webApplication.qualityInfrastructure -> molinex.apiApplication "Reads and writes quality data using" "JSON/HTTPS REST"

molinex.webApplication.machineList -> molinex.webApplication.maintenanceApplication "Reads and administers machines through"
molinex.webApplication.machineForm -> molinex.webApplication.maintenanceApplication "Registers and updates machines through"
molinex.webApplication.machineStatusView -> molinex.webApplication.maintenanceApplication "Reads machine status from"
molinex.webApplication.maintenanceRecordForm -> molinex.webApplication.maintenanceApplication "Submits maintenance records through"
molinex.webApplication.maintenanceHistoryView -> molinex.webApplication.maintenanceApplication "Reads maintenance history from"
molinex.webApplication.machineList -> molinex.webApplication.maintenanceDomain "Displays"
molinex.webApplication.machineForm -> molinex.webApplication.maintenanceDomain "Builds"
molinex.webApplication.machineStatusView -> molinex.webApplication.maintenanceDomain "Displays"
molinex.webApplication.maintenanceRecordForm -> molinex.webApplication.maintenanceDomain "Builds"
molinex.webApplication.maintenanceHistoryView -> molinex.webApplication.maintenanceDomain "Displays"
molinex.webApplication.maintenanceApplication -> molinex.webApplication.maintenanceDomain "Holds"
molinex.webApplication.maintenanceApplication -> molinex.webApplication.maintenanceInfrastructure "Loads and saves asset data through"
molinex.webApplication.maintenanceInfrastructure -> molinex.webApplication.maintenanceDomain "Builds"
molinex.webApplication.maintenanceInfrastructure -> molinex.apiApplication "Reads and writes asset and maintenance data using" "JSON/HTTPS REST"

molinex.webApplication.operationalVariableDashboard -> molinex.webApplication.intelligenceApplication "Reads operational readings from"
molinex.webApplication.anomalyList -> molinex.webApplication.intelligenceApplication "Reads anomalies from"
molinex.webApplication.alertList -> molinex.webApplication.intelligenceApplication "Reads and attends alerts through"
molinex.webApplication.maintenanceRecommendationList -> molinex.webApplication.intelligenceApplication "Reads recommendations from"
molinex.webApplication.operationalVariableDashboard -> molinex.webApplication.intelligenceDomain "Displays"
molinex.webApplication.anomalyList -> molinex.webApplication.intelligenceDomain "Displays"
molinex.webApplication.alertList -> molinex.webApplication.intelligenceDomain "Displays"
molinex.webApplication.maintenanceRecommendationList -> molinex.webApplication.intelligenceDomain "Displays"
molinex.webApplication.intelligenceApplication -> molinex.webApplication.intelligenceDomain "Holds"
molinex.webApplication.intelligenceApplication -> molinex.webApplication.intelligenceInfrastructure "Loads monitoring data through"
molinex.webApplication.intelligenceInfrastructure -> molinex.webApplication.intelligenceDomain "Builds"
molinex.webApplication.intelligenceInfrastructure -> molinex.apiApplication "Reads monitoring data and attends alerts using" "JSON/HTTPS REST"

molinex.webApplication.operationalSummaryView -> molinex.webApplication.reportingApplication "Reads the operational summary from"
molinex.webApplication.productionReportView -> molinex.webApplication.reportingApplication "Requests production reports through"
molinex.webApplication.maintenanceReportView -> molinex.webApplication.reportingApplication "Requests maintenance reports through"
molinex.webApplication.trendDashboard -> molinex.webApplication.reportingApplication "Reads trends from"
molinex.webApplication.operationalSummaryView -> molinex.webApplication.reportingDomain "Displays"
molinex.webApplication.productionReportView -> molinex.webApplication.reportingDomain "Displays"
molinex.webApplication.maintenanceReportView -> molinex.webApplication.reportingDomain "Displays"
molinex.webApplication.trendDashboard -> molinex.webApplication.reportingDomain "Displays"
molinex.webApplication.reportingApplication -> molinex.webApplication.reportingDomain "Holds"
molinex.webApplication.reportingApplication -> molinex.webApplication.reportingInfrastructure "Loads summaries, reports and trends through"
molinex.webApplication.reportingInfrastructure -> molinex.webApplication.reportingDomain "Builds"
molinex.webApplication.reportingInfrastructure -> molinex.apiApplication "Reads reporting projections using" "JSON/HTTPS REST"

molinex.webApplication.appLayout -> molinex.webApplication.navigationMenu "Renders"
molinex.webApplication.appLayout -> molinex.webApplication.sharedViews "Hosts"
molinex.webApplication.appLayout -> molinex.webApplication.feedbackMessage "Renders"

molinex.landingPage -> molinex.apiApplication.commercialModule "Uses"
molinex.webApplication -> molinex.apiApplication.identityModule "Uses"
molinex.webApplication -> molinex.apiApplication.productionModule "Uses"
molinex.webApplication -> molinex.apiApplication.qualityModule "Uses"
molinex.webApplication -> molinex.apiApplication.maintenanceModule "Uses"
molinex.webApplication -> molinex.apiApplication.intelligenceModule "Uses"
molinex.webApplication -> molinex.apiApplication.reportingModule "Uses"
sensorGateway -> molinex.apiApplication.intelligenceModule "Sends measurements to" "HTTPS or MQTT"
molinex.apiApplication.identityModule -> notificationService "Sends account notifications through"
molinex.apiApplication.intelligenceModule -> notificationService "Sends operational alerts through"
molinex.apiApplication.productionModule -> molinex.apiApplication.qualityModule "Publishes production events"
molinex.apiApplication.qualityModule -> molinex.apiApplication.intelligenceModule "Publishes quality deviations"
molinex.apiApplication.maintenanceModule -> molinex.apiApplication.intelligenceModule "Publishes asset events"
molinex.apiApplication.intelligenceModule -> molinex.apiApplication.maintenanceModule "Publishes anomalies"
molinex.apiApplication.productionModule -> molinex.apiApplication.reportingModule "Publishes production events"
molinex.apiApplication.qualityModule -> molinex.apiApplication.reportingModule "Publishes quality events"
molinex.apiApplication.maintenanceModule -> molinex.apiApplication.reportingModule "Publishes maintenance events"
molinex.apiApplication.intelligenceModule -> molinex.apiApplication.reportingModule "Publishes alert events"
molinex.apiApplication.productionModule -> molinex.apiApplication.sharedKernel "Uses shared values"
molinex.apiApplication.qualityModule -> molinex.apiApplication.sharedKernel "Uses shared values"
molinex.apiApplication.commercialModule -> molinex.database "Owns commercial inquiry and plan data in" "EF Core/SQL"
molinex.apiApplication.identityModule -> molinex.database "Owns identity and authorization data in" "EF Core/SQL"
molinex.apiApplication.productionModule -> molinex.database "Owns production data in" "EF Core/SQL"
molinex.apiApplication.qualityModule -> molinex.database "Owns quality and yield data in" "EF Core/SQL"
molinex.apiApplication.maintenanceModule -> molinex.database "Owns machine and maintenance data in" "EF Core/SQL"
molinex.apiApplication.intelligenceModule -> molinex.database "Owns reading, anomaly and alert data in" "EF Core/SQL"
molinex.apiApplication.reportingModule -> molinex.database "Owns reporting projections in" "EF Core/SQL"

molinex.landingPage -> molinex.apiApplication.planCatalogInterfaces "Requests plans and the value proposition from" "JSON/HTTPS REST"
molinex.landingPage -> molinex.apiApplication.commercialInquiryInterfaces "Submits commercial inquiries to" "JSON/HTTPS REST"
molinex.apiApplication.planCatalogInterfaces -> molinex.apiApplication.commercialQueryServices "Delegates queries to"
molinex.apiApplication.commercialInquiryInterfaces -> molinex.apiApplication.commercialCommandServices "Delegates commands to"
molinex.apiApplication.commercialCommandServices -> molinex.apiApplication.commercialDomain "Uses"
molinex.apiApplication.commercialQueryServices -> molinex.apiApplication.commercialDomain "Reads from"
molinex.apiApplication.commercialCommandServices -> molinex.apiApplication.commercialInfrastructure "Persists through"
molinex.apiApplication.commercialQueryServices -> molinex.apiApplication.commercialInfrastructure "Loads through"
molinex.apiApplication.commercialInfrastructure -> molinex.apiApplication.commercialDomain "Implements repository and event-publication ports defined by"
molinex.apiApplication.commercialInfrastructure -> molinex.database "Persists commercial data in" "EF Core/SQL"

molinex.webApplication -> molinex.apiApplication.authenticationInterfaces "Invokes authentication operations on" "JSON/HTTPS REST"
molinex.webApplication -> molinex.apiApplication.userAdministrationInterfaces "Invokes user-administration operations on" "JSON/HTTPS REST"
molinex.webApplication -> molinex.apiApplication.profileInterfaces "Invokes profile operations on" "JSON/HTTPS REST"
molinex.apiApplication.authenticationInterfaces -> molinex.apiApplication.identityCommandServices "Delegates commands to"
molinex.apiApplication.userAdministrationInterfaces -> molinex.apiApplication.identityCommandServices "Delegates commands to"
molinex.apiApplication.userAdministrationInterfaces -> molinex.apiApplication.identityQueryServices "Delegates queries to"
molinex.apiApplication.profileInterfaces -> molinex.apiApplication.identityCommandServices "Delegates commands to"
molinex.apiApplication.profileInterfaces -> molinex.apiApplication.identityQueryServices "Delegates queries to"
molinex.apiApplication.identityCommandServices -> molinex.apiApplication.identityDomain "Uses"
molinex.apiApplication.identityQueryServices -> molinex.apiApplication.identityDomain "Reads from"
molinex.apiApplication.identityCommandServices -> molinex.apiApplication.identityInfrastructure "Persists and notifies through"
molinex.apiApplication.identityQueryServices -> molinex.apiApplication.identityInfrastructure "Loads through"
molinex.apiApplication.identityInfrastructure -> molinex.apiApplication.identityDomain "Implements security, notification and repository ports defined by"
molinex.apiApplication.identityInfrastructure -> molinex.database "Persists identity data in" "EF Core/SQL"
molinex.apiApplication.identityInfrastructure -> notificationService "Delivers account notifications through" "HTTPS API or SMTP"

molinex.webApplication -> molinex.apiApplication.rawMaterialReceptionInterfaces "Invokes reception operations on" "JSON/HTTPS REST"
molinex.webApplication -> molinex.apiApplication.productionBatchInterfaces "Invokes batch operations on" "JSON/HTTPS REST"
molinex.webApplication -> molinex.apiApplication.productionRecordInterfaces "Invokes production-record operations on" "JSON/HTTPS REST"
molinex.apiApplication.rawMaterialReceptionInterfaces -> molinex.apiApplication.productionCommandServices "Delegates commands to"
molinex.apiApplication.rawMaterialReceptionInterfaces -> molinex.apiApplication.productionQueryServices "Delegates queries to"
molinex.apiApplication.productionBatchInterfaces -> molinex.apiApplication.productionCommandServices "Delegates commands to"
molinex.apiApplication.productionBatchInterfaces -> molinex.apiApplication.productionQueryServices "Delegates queries to"
molinex.apiApplication.productionRecordInterfaces -> molinex.apiApplication.productionCommandServices "Delegates commands to"
molinex.apiApplication.productionRecordInterfaces -> molinex.apiApplication.productionQueryServices "Delegates queries to"
molinex.apiApplication.productionCommandServices -> molinex.apiApplication.productionDomain "Uses"
molinex.apiApplication.productionQueryServices -> molinex.apiApplication.productionDomain "Reads from"
molinex.apiApplication.productionCommandServices -> molinex.apiApplication.productionInfrastructure "Persists through"
molinex.apiApplication.productionQueryServices -> molinex.apiApplication.productionInfrastructure "Loads through"
molinex.apiApplication.productionInfrastructure -> molinex.apiApplication.productionDomain "Implements repository and event-publication ports defined by"
molinex.apiApplication.productionInfrastructure -> molinex.database "Persists production data in" "EF Core/SQL"

molinex.webApplication -> molinex.apiApplication.qualityAssessmentInterfaces "Invokes quality-assessment operations on" "JSON/HTTPS REST"
molinex.webApplication -> molinex.apiApplication.wasteRecordInterfaces "Invokes waste-record operations on" "JSON/HTTPS REST"
molinex.webApplication -> molinex.apiApplication.yieldAnalysisInterfaces "Invokes yield-analysis operations on" "JSON/HTTPS REST"
molinex.apiApplication.qualityAssessmentInterfaces -> molinex.apiApplication.qualityCommandServices "Delegates commands to"
molinex.apiApplication.qualityAssessmentInterfaces -> molinex.apiApplication.qualityQueryServices "Delegates queries to"
molinex.apiApplication.wasteRecordInterfaces -> molinex.apiApplication.qualityCommandServices "Delegates commands to"
molinex.apiApplication.wasteRecordInterfaces -> molinex.apiApplication.qualityQueryServices "Delegates queries to"
molinex.apiApplication.yieldAnalysisInterfaces -> molinex.apiApplication.qualityQueryServices "Delegates queries to"
molinex.apiApplication.qualityCommandServices -> molinex.apiApplication.qualityDomain "Uses"
molinex.apiApplication.qualityQueryServices -> molinex.apiApplication.qualityDomain "Reads from"
molinex.apiApplication.qualityCommandServices -> molinex.apiApplication.qualityInfrastructure "Persists through"
molinex.apiApplication.qualityQueryServices -> molinex.apiApplication.qualityInfrastructure "Loads through"
molinex.apiApplication.qualityInfrastructure -> molinex.apiApplication.qualityDomain "Implements repository and event-publication ports defined by"
molinex.apiApplication.qualityInfrastructure -> molinex.database "Persists quality and yield data in" "EF Core/SQL"

molinex.webApplication -> molinex.apiApplication.machineInterfaces "Invokes machine operations on" "JSON/HTTPS REST"
molinex.webApplication -> molinex.apiApplication.maintenanceRecordInterfaces "Invokes maintenance operations on" "JSON/HTTPS REST"
molinex.apiApplication.machineInterfaces -> molinex.apiApplication.maintenanceCommandServices "Delegates commands to"
molinex.apiApplication.machineInterfaces -> molinex.apiApplication.maintenanceQueryServices "Delegates queries to"
molinex.apiApplication.maintenanceRecordInterfaces -> molinex.apiApplication.maintenanceCommandServices "Delegates commands to"
molinex.apiApplication.maintenanceRecordInterfaces -> molinex.apiApplication.maintenanceQueryServices "Delegates queries to"
molinex.apiApplication.maintenanceCommandServices -> molinex.apiApplication.maintenanceDomain "Uses"
molinex.apiApplication.maintenanceQueryServices -> molinex.apiApplication.maintenanceDomain "Reads from"
molinex.apiApplication.maintenanceCommandServices -> molinex.apiApplication.maintenanceInfrastructure "Persists through"
molinex.apiApplication.maintenanceQueryServices -> molinex.apiApplication.maintenanceInfrastructure "Loads through"
molinex.apiApplication.maintenanceInfrastructure -> molinex.apiApplication.maintenanceDomain "Implements repository and event-publication ports defined by"
molinex.apiApplication.maintenanceInfrastructure -> molinex.database "Persists asset and maintenance data in" "EF Core/SQL"

sensorGateway -> molinex.apiApplication.telemetryIngestionInterfaces "Sends operational readings to" "HTTPS or MQTT"
molinex.webApplication -> molinex.apiApplication.monitoringInterfaces "Invokes monitoring operations on" "JSON/HTTPS REST"
molinex.apiApplication.telemetryIngestionInterfaces -> molinex.apiApplication.intelligenceCommandServices "Delegates reading commands to"
molinex.apiApplication.monitoringInterfaces -> molinex.apiApplication.intelligenceCommandServices "Delegates alert commands to"
molinex.apiApplication.monitoringInterfaces -> molinex.apiApplication.intelligenceQueryServices "Delegates queries to"
molinex.apiApplication.intelligenceCommandServices -> molinex.apiApplication.intelligenceDomain "Uses"
molinex.apiApplication.intelligenceQueryServices -> molinex.apiApplication.intelligenceDomain "Reads from"
molinex.apiApplication.intelligenceCommandServices -> molinex.apiApplication.intelligenceInfrastructure "Persists and notifies through"
molinex.apiApplication.intelligenceQueryServices -> molinex.apiApplication.intelligenceInfrastructure "Loads through"
molinex.apiApplication.intelligenceInfrastructure -> molinex.apiApplication.intelligenceDomain "Implements telemetry, notification and repository ports defined by"
molinex.apiApplication.intelligenceInfrastructure -> molinex.database "Persists readings, anomalies and alerts in" "EF Core/SQL"
molinex.apiApplication.intelligenceInfrastructure -> notificationService "Delivers operational alerts through" "HTTPS API"

molinex.webApplication -> molinex.apiApplication.reportingInterfaces "Invokes reporting queries on" "JSON/HTTPS REST"
molinex.apiApplication.reportingInterfaces -> molinex.apiApplication.reportingQueryServices "Delegates report queries to"
molinex.apiApplication.reportingQueryServices -> molinex.apiApplication.reportingDomain "Reads from"
molinex.apiApplication.reportingQueryServices -> molinex.apiApplication.reportingInfrastructure "Loads through"
molinex.apiApplication.reportingProjectionHandlers -> molinex.apiApplication.reportingDomain "Builds projections defined by"
molinex.apiApplication.reportingProjectionHandlers -> molinex.apiApplication.reportingInfrastructure "Updates projections through"
molinex.apiApplication.reportingInfrastructure -> molinex.apiApplication.reportingDomain "Implements projection repository ports defined by"
molinex.apiApplication.reportingInfrastructure -> molinex.database "Reads and stores reporting projections in" "EF Core/SQL"

molinex.apiApplication.productionDomain -> molinex.apiApplication.sharedKernelDomain "Uses Weight and MeasurementUnit from"
molinex.apiApplication.qualityDomain -> molinex.apiApplication.sharedKernelDomain "Uses Weight and MeasurementUnit from"
molinex.webApplication.productionDomain -> molinex.webApplication.sharedKernelDomain "Uses Weight and MeasurementUnit from"
molinex.webApplication.qualityDomain -> molinex.webApplication.sharedKernelDomain "Uses Weight and MeasurementUnit from"
